import os

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
GOOGLE_CSE_ID = os.getenv("GOOGLE_CSE_ID")
HUGGINGFACEHUB_API_TOKEN = os.getenv("HUGGINGFACEHUB_API_TOKEN")
QDRANT_COLLECTION_NAME_1 = os.getenv("QDRANT_COLLECTION_NAME_1")
QDRANT_COLLECTION_ISLAMIC = os.getenv("QDRANT_COLLECTION_ISLAMIC")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY")
QDRANT_HOST = os.getenv("QDRANT_HOST")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
